USE QLPK_CSDL
GO
--XEM TẤT CẢ LOẠI ÐIỀU TRỊ
--RETURN TABLE: MÃ DANH MỤC, TÊN DANH MỤC, MÃ ÐIỀU TRỊ, TÊN ÐIỀU TRỊ
CREATE FUNCTION LAYTATCADIEUTRI()
RETURNS TABLE
AS
	RETURN (SELECT LDT.MADANHMUC , DM.TENDM , LDT.MADIEUTRI , LDT.TENDIEUTRI  
			FROM LOAIDIEUTRI LDT JOIN DANHMUCDIEUTRI DM ON LDT.MADANHMUC = DM.MADANHMUC)
GO

--LẤY DANH SÁCH BUỔI ĐIỀU TRỊ THEO BỆNH NHÂN VÀ SẮP XẾP THEO NGÀY
CREATE OR ALTER PROC LAYBUOIDT_BN
	@MABENHNHAN CHAR(8)
AS
BEGIN TRAN
	BEGIN TRY
		--KIỂM TRA ÐIỀU KIỆN
		--IF NOT EXISTS (SELECT HSBN.IDBENHNHAN
		--				FROM HOSOBENHNHAN HSBN
		--				WHERE HSBN.IDBENHNHAN = @MABENHNHAN)
		--	BEGIN
		--		PRINT N'KHÔNG TÌM THẤY BỆNH NHÂN'
		--		ROLLBACK TRAN
		--		RETURN 1
		--	END
		--THỰC THI
		SELECT *
		FROM BUOIDIEUTRI BDT 
		WHERE BDT.BNKHAMLE = @MABENHNHAN
		ORDER BY BDT.NGAYDT DESC
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO

EXEC LAYBUOIDT_BN 'BN030190'
GO

--LẤY DANH SÁCH BUỔI ĐIỀU TRỊ TỪ NGÀY A->B
CREATE OR ALTER PROC LAYBUOIDT_NGAY
	@DATEA DATE,
	@DATEB DATE
AS
BEGIN TRAN
	BEGIN TRY
		--KIỂM TRA ÐIỀU KIỆN
		IF @DATEA > @DATEB
		BEGIN
			DECLARE @TEMP DATE
			SET @TEMP = @DATEA
			SET @DATEA = @DATEB
			SET @DATEB = @TEMP
		END
		PRINT @DATEA
		PRINT @DATEB
		--THỰC THI
		SELECT *
		FROM BUOIDIEUTRI BDT 
		WHERE BDT.NGAYDT >= @DATEA AND BDT.NGAYDT <= @DATEB
		ORDER BY BDT.NGAYDT DESC
	
	END TRY
	BEGIN CATCH
		PRINT N'LỖI HỆ THỐNG'
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO

EXEC LAYBUOIDT_NGAY '2023-12-7','2023-12-1'
