CREATE OR ALTER PROC SP_XEMDANHSACHDONTHUOCBN 
	@IDBENHNHAN CHAR(8)
AS
BEGIN TRAN
	BEGIN TRY
	SELECT DT.IDDONTHUOC, DT.NGAYCAP, DT.IDBUOIDIEUTRI, BN.TENBN, SUM(CT.SOLUONG * T.GIATHUOC) AS 'GIA'
	FROM DONTHUOC DT, CHITIETDONTHUOC CT, THUOC T, BUOIDIEUTRI BDT, HOSOBENHNHAN BN
	WHERE CT.IDTHUOC = T.IDTHUOC AND BDT.BNKHAMLE = @IDBENHNHAN AND BDT.IDBUOIDIEUTRI = DT.IDBUOIDIEUTRI AND DT.IDDONTHUOC = CT.IDDONTHUOC AND BN.IDBENHNHAN=@IDBENHNHAN
	GROUP BY DT.IDDONTHUOC, DT.NGAYCAP, DT.IDBUOIDIEUTRI, BN.TENBN
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage;
		ROLLBACK TRAN
		RETURN 2
	END CATCH
COMMIT TRAN
RETURN 0
GO

CREATE OR ALTER PROC SP_XEMCHITIETDONTHUOC 
	@IDDONTHUOC CHAR(12)
AS
BEGIN TRAN
	BEGIN TRY
	DECLARE @TONGGIA FLOAT
	SET @TONGGIA = (SELECT SUM(T.GIATHUOC * CT.SOLUONG) FROM CHITIETDONTHUOC CT JOIN THUOC T ON CT.IDTHUOC = T.IDTHUOC WHERE CT.IDDONTHUOC = @IDDONTHUOC GROUP BY CT.IDDONTHUOC)
	SELECT CT.IDTHUOC , T.TENTHUOC, CT.SOLUONG, T.GIATHUOC * CT.SOLUONG as 'GIA', @TONGGIA 'TONGGIA'
	FROM CHITIETDONTHUOC CT, THUOC T, DONTHUOC D
	WHERE D.IDDONTHUOC = @IDDONTHUOC AND CT.IDDONTHUOC = D.IDDONTHUOC AND T.IDTHUOC = CT.IDTHUOC
	
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS ErrorMessage;
		ROLLBACK TRAN
		RETURN 2
	END CATCH
COMMIT TRAN
RETURN 0
GO