CREATE OR ALTER PROC SP_XEMDANHSACHHOADONBN
	@IDBENHNHAN CHAR(8)
	
AS
BEGIN TRAN
	BEGIN TRY
		IF NOT EXISTS (SELECT * FROM HOSOBENHNHAN WHERE IDBENHNHAN=@IDBENHNHAN)
		BEGIN
			ROLLBACK TRAN
			RETURN 1
		END
		
		SELECT HD.IDHOADON, HD.TONGTIEN, HD.NGAYGIAODICH, HD.GHICHUHOADON, BN.TENBN, HD.IDBUOIDIEUTRI
		FROM HOADON HD JOIN HOSOBENHNHAN BN ON HD.IDBENHNHAN = BN.IDBENHNHAN
		WHERE BN.IDBENHNHAN = @IDBENHNHAN
	END TRY
	 
	BEGIN CATCH
		ROLLBACK TRAN
		RETURN 2
	END CATCH
COMMIT TRAN
RETURN 0
GO

CREATE OR ALTER PROC SP_XEMCHITIETHOADON
	@IDHOADON CHAR(15)
AS
BEGIN TRAN
	BEGIN TRY 
		IF NOT EXISTS (SELECT * FROM HOADON WHERE IDHOADON=@IDHOADON)
		BEGIN
			ROLLBACK TRAN
			RETURN 1
		END
		DECLARE @IDBUOIDIEUTRI CHAR(10)
		SET @IDBUOIDIEUTRI = (SELECT BDT.IDBUOIDIEUTRI FROM HOADON HD JOIN BUOIDIEUTRI BDT ON HD.IDBUOIDIEUTRI = BDT.IDBUOIDIEUTRI 
									WHERE HD.IDHOADON = @IDHOADON)
		
		SELECT HD.IDHOADON, HD.TONGTIEN, HD.LOAITHANHTOAN, HD.GHICHUHOADON, HD.NGAYGIAODICH
		FROM HOADON HD WHERE HD.IDHOADON = @IDHOADON

		SELECT CTDT.IDBUOIDIEUTRI, LDT.MADIEUTRI, LDT.TENDIEUTRI, LDT.GIA
		FROM CHITIETDIEUTRI CTDT JOIN LOAIDIEUTRI LDT ON CTDT.MADIEUTRI = LDT.MADIEUTRI
		WHERE CTDT.IDBUOIDIEUTRI = @IDBUOIDIEUTRI

		SELECT T.IDTHUOC, T.TENTHUOC, CT.SOLUONG, T.GIATHUOC * CT.SOLUONG 'GIATHUOC'
		FROM DONTHUOC DT JOIN CHITIETDONTHUOC CT ON CT.IDDONTHUOC = DT.IDDONTHUOC
		JOIN THUOC T ON T.IDTHUOC=CT.IDTHUOC
		WHERE DT.IDBUOIDIEUTRI = @IDBUOIDIEUTRI
	END TRY
	BEGIN CATCH
		ROLLBACK TRAN
		RETURN 2
	END CATCH
COMMIT TRAN
RETURN 0
GO