--FORMAT INPUT: YYYY - MM - DD
-- 1. Xem danh sách lịch hẹn của 1 bệnh nhân theo ngày
CREATE OR ALTER PROC SP_XEM_LICH_HEN_BN
	@ID_BENHNHAN CHAR(8),
	@NGAY DATE
AS
BEGIN TRAN
	BEGIN TRY
		SELECT BN.TENBN, BN.IDBENHNHAN, LH.NGAYHEN, LH.THOIGIANHEN, LH.TINHTRANG, LH.PHONG, LH.GHICHULICHHEN, LH.BACSI, LH.TROKHAM
		FROM LICHHEN LH
		JOIN HOSOBENHNHAN BN ON LH.BENHNHAN = BN.IDBENHNHAN
		WHERE BN.IDBENHNHAN = @ID_BENHNHAN AND LH.NGAYHEN = @NGAY
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS errormessage
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO

--EXEC SP_XEM_LICH_HEN_BN 'BN005521', '2020-10-04'
GO
EXEC SP_XEM_LICH_HEN_BN 'BN000006','2022-10-11'
GO

-- 2. Xem danh sách lịch hẹn của phòng khám theo ngày
CREATE OR ALTER PROC SP_XEM_LICH_HEN_PK
	@ID_PHONGKHAM CHAR(3),
	@NGAY DATE
AS
BEGIN TRAN
	BEGIN TRY
		SELECT PK.TENPK, LH.*
		FROM LICHHEN LH
		JOIN PHONGKHAM PK ON LH.PHONG = PK.IDPHONGKHAM
		WHERE PK.IDPHONGKHAM = @ID_PHONGKHAM AND LH.NGAYHEN = @NGAY
	END TRY
	BEGIN CATCH
		SELECT ERROR_MESSAGE() AS errormessage
		ROLLBACK TRAN
		RETURN 1
	END CATCH
COMMIT TRAN
RETURN 0
GO

EXEC SP_XEM_LICH_HEN_PK 'P01','2023-12-09'
GO